name: Iac Workflow (Terraform)
run-name: terraform ${{ inputs.action }}-${{ inputs.env }}

on:
  workflow_dispatch:
    inputs:
      action:
        description: Terraform Action
        type: choice
        options:
          - plan
          - apply
          - destroy
        required: true

      env:
        description: Environment
        type: choice
        options:
          - dev
          - prod
        required: true

jobs:
  terraform-action:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Github Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # تأكدي أن هذه المنطقة هي نفس منطقة الـ S3 Bucket والـ VPC أو عدليها حسب الحاجة
          aws-region: eu-west-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # نقوم بعمل init عادي، ويفضل دائماً التأكد من صيغة الكود قبل التنفيذ
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: ${{ inputs.action == 'plan' }}
        run: terraform plan -var-file="${{ inputs.env }}.tfvars"

      - name: Terraform Apply
        if: ${{ inputs.action == 'apply' }}
        run: terraform apply -auto-approve -var-file="${{ inputs.env }}.tfvars"

      - name: Terraform Destroy
        if: ${{ inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve -var-file="${{ inputs.env }}.tfvars"